export { shorten } from "./shorten"
export { CompareEnd } from "./CompareEnd"
export { toCamelCase } from "./toCamelCase"
export { toKebabCase } from "./toKebabCase"
export { toSnakeCase } from "./toSnakeCase"
export {shorten} from "./shorten"
export {StartsWith} from "./StartsWith"
export { CompareEnd } from "./CompareEnd"
export { pol} from "./polindrom"
export {toUppeFirst} from "./toUpperFirst"
export {countWords} from "./countWords"